### ISSUE TITLE
Docs : To-Do

### ISSUE THREAD

**Issue by Puri12** [Puri12/TIL#1]
## 일반 포스트

- [ ] 2022 회고

## 기술 포스트

- [ ] Docker 소개 및 장단점
- [ ] Go Lang 소개
- [ ] Spring 세세한 부분 정리
